### ISSUE TITLE
Wrong Saturation/Brightness/Colour

### ISSUE THREAD

**Issue by DasPflanze** [dotsam/homebridge-milight#24] opened 2017-02-15 14:11 UTC
In my setup (1 RasPi, 1 iBox2, 2 RGB Controller, 2 IKEA Dioder) everything works fine, but the staturation is wrong. Also setting the colourwheel to white, changes the LED to red. Setting it slightly beside the center activates the white mode, but the brightness is set too low. So i have to increase the brightness manually to get the full white mode. 

![pjimage](https://cloud.githubusercontent.com/assets/13289288/22977697/074bdc3c-f390-11e6-8ae1-471f09f44b8d.jpg)
 
![pjimage 1](https://cloud.githubusercontent.com/assets/13289288/22977936/f5999bc2-f390-11e6-8779-9616eb6ee934.jpg)

**Comment by SkyJohn** [comment] 2017-02-16 20:38
The colours are changing correctly, the way Apple displays the colour wheel in the Home app is just misleading.

If you look at the colour wheel in the mi-light app you can see why you're getting the same colours when you move into the inner area of the wheel.
![img_2508](https://cloud.githubusercontent.com/assets/7078053/23040047/cb169af6-f487-11e6-8803-4d59524223ac.png)

**Comment by mwittig** [comment] 2017-03-04 12:00
@dotsam @DasPflanze I think the problem is a glitch in the Milight full color model. Different to what you may expect from HSV and HSL color models a saturation value of 100 does not mean 100% saturation, but it is 0% saturation. In other words the saturation value is inverted. I'll look into this asap as part of the underlying lib node-milight-promise to add an option for automatically inverting the saturation value. It should also be possible to fix it right away as part of homebridge-milight, however.

**Comment by DasPflanze** [comment] 2017-03-05 10:35
Ok, it sounds logical. Thank you very much!

**Comment by dotsam** [comment] 2017-03-05 19:15
I've implemented this in the dev branch, if you want to install that and see how it works. Thanks!

**Comment by dotsam** [comment] 2017-03-13 20:32
This has been confirmed to be fixed by testers in #19, so I'll be pushing a new version to npm shortly.

**Closed as completed** 2017-03-13 20:36 UTC
